update wf

diff --git a/.github/workflows/release-workflow.yml b/.github/workflows/release-workflow.yml
--- a/.github/workflows/release-workflow.yml
+++ b/.github/workflows/release-workflow.yml
@@ -205,14 +205,26 @@ jobs:
           echo "doc_file=${{ needs.variables.outputs.DOC_PATH }}$doc_file" >> $GITHUB_OUTPUT
 
       - name: Upload doc file to release assets
-        uses: actions/upload-release-asset@v1
-        with:
-          upload_url: ${{ steps.create_release_draft.outputs.upload_url }}
-          asset_path: ${{ steps.create_release_draft.outputs.doc_file }}
-          asset_name: ${{ steps.create_release_draft.outputs.doc_file }}
-          asset_content_type: text/html
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        id: upload_documentation
+        run: |
+          ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}
+          REPO_NAME=${{ github.repository }}
+          RELEASE_ID=${{ needs.release.outputs.RELEASE_ID }}
+
+          RELEASE_ASSET=${{ steps.create_release_draft.outputs.doc_file }}
+
+          RESPONSE=$(curl -sS -i -X POST \
+            -H "Authorization: Bearer $ACCESS_TOKEN" \
+            -H "Content-Type: application/octet-stream" \
+            --data-binary "@$RELEASE_ASSET" \
+            https://uploads.github.com/repos/$REPO_NAME/releases/$RELEASE_ID/assets?name=$RELEASE_ASSET)
+
+          if [[ $(echo $RESPONSE | head -n 1 | cut -d$' ' -f2 ) -ne 201 ]]; then
+            echo "Failed to upload release asset $RELEASE_ASSET. Received response from GitHub API:"
+            echo ""
+            echo "$RESPONSE"
+            exit 1
+          fi
 
   rollback:
     runs-on: ubuntu-latest
